/*
 * JSP generated by Resin-3.1.15 (built Mon, 13 Oct 2014 06:45:33 PDT)
 */

package _jsp._sysop._user;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.io.IOException;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _user_0excel__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write('\n');
      

String docRoot = Config.getDocRoot();
String jndi = Config.getJndi();
String tplRoot = Config.getDocRoot() + "/sysop/html";

Malgn m = new Malgn(request, response, out);

Form f = new Form("form1");
try { f.setRequest(request); } catch (Exception ex) { out.print("\uc81c\ud55c \uc6a9\ub7c9 \ucd08\uacfc - " + ex.getMessage()); return; }

Page p = new Page(tplRoot);
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);
p.setBaseRoot("/home/lms/public_html/html");

SiteDao Site = new SiteDao();
DataSet siteinfo = Site.getSiteInfo(request.getServerName(), "sysop");
SiteConfigDao SiteConfig = new SiteConfigDao(siteinfo.i("id"));
if(1 != siteinfo.i("sysop_status") || "".equals(siteinfo.s("doc_root"))
|| (14 == siteinfo.s("close_date").length()
&& 0 < m.diffDate("I", siteinfo.s("close_date"), m.time("yyyyMMddHHmmss")))
) {
	m.jsReplace("/main/guide.jsp", "top"); return; }
//Hashtable<String, String> siteconfig = SiteConfig.getSiteConfig(siteinfo.s("id"));

String siteDomain = request.getScheme() + "://" + request.getServerName();
int port = request.getServerPort();
if(port != 80) siteDomain += ":" + port;
String webUrl = siteDomain + "/sysop";

String dataDir = siteinfo.s("doc_root") + "/data";
f.dataDir = dataDir;
m.dataDir = dataDir;
m.dataUrl = Config.getDataUrl() + (!"/data".equals(Config.getDataUrl()) ? siteinfo.s("ftp_id") : "");

boolean isDevServer = -1 < request.getServerName().indexOf("lms.malgn.co.kr");
siteinfo.put("logo_url", (!"/data".equals(Config.getDataUrl()) ? "" : siteDomain) + m.getUploadUrl(siteinfo.s("logo")));

//IP\ucc28\ub2e8
String userIp = request.getRemoteAddr();
boolean isMalgnOffice = "106.244.224.183".equals(userIp) || "125.129.123.211".equals(userIp) || "59.5.222.106".equals(userIp) || "3.35.211.181".equals(userIp);
if(!"".equals(siteinfo.s("allow_ip_sysop")) && !isMalgnOffice && !Site.checkIP(userIp, siteinfo.s("allow_ip_sysop"))) {
	m.redirect("/");
	return;
}

//\uc5b8\uc5b4
String sysLocale = "".equals(siteinfo.s("locale")) ? "default" : siteinfo.s("locale");
//String sysLocale = "default";
Message _message = new Message(sysLocale);
_message.reloadAll();
m.setMessage(_message);
//p.setMessage(_message);

//\uae30\ubcf8 \ud68c\uc6d0\uc815\ubcf4
int siteId = siteinfo.i("id");
int userId = 0;
String loginId = "";
String userName = "";
String userKind = "";
int userDeptId = 0;
String userGroups = "";
String manageCourses = "";
String userSessionId = "";
String pagreeDate = "";
boolean isUserMaster = false;
String winTitle = "[\uad00\ub9ac\uc790] " + siteinfo.s("site_nm");
String sysToday = m.time("yyyyMMdd");
String sysNow = m.time("yyyyMMddHHmmss");
String surl = request.getRequestURL() + (!"".equals(m.qs()) ? "?" + m.qs() : "");
final int sysExcelCnt = 20000;

SessionDao mSession = new SessionDao(request, response);

//\ub85c\uadf8\uc778 \uc5ec\ubd80\ub97c \uccb4\ud06c
Auth auth = new Auth(request, response);
auth.loginURL = "/sysop/main/login.jsp";
auth.keyName = "MLMSKEY2014" + siteId + "7";
if(0 < siteinfo.i("sysop_session_hour")) auth.setValidTime(siteinfo.i("sysop_session_hour") * 60);
if(auth.isValid()) {
	userId = m.parseInt(auth.getString("ID"));
	loginId = auth.getString("LOGINID");
	userName = auth.getString("NAME");
	userKind = auth.getString("KIND");
	userDeptId = auth.getInt("DEPT");
	userGroups = auth.getString("GROUPS");
	manageCourses = auth.getString("MANAGE_COURSES");
	userSessionId = userSessionId = auth.getString("SESSIONID");
	pagreeDate = auth.getString("PAGREE_DATE");
	isUserMaster = "Y".equals(auth.getString("IS_USER_MASTER"));

	//2\ucc28\uc778\uc99d\uccb4\ud06c
	/*if("Y".equals(siteinfo.s("auth2_yn"))
		&&!"Y".equals(auth.getString("AUTH2_YN"))
		&& !"".equals(siteinfo.s("auth2_type"))
		&& !"malgn".equals(loginId)
		&& request.getRequestURI().indexOf("/main/auth2.jsp") == -1
		&& request.getRequestURI().indexOf("/main/otpkey_register.jsp") == -1
		&& request.getRequestURI().indexOf("/sysop/main/logout.jsp") == -1
	) {
		m.jsReplace("/sysop/main/auth2.jsp?returl=" + m.rs("returl", "/sysop/index.jsp"), "top");
		return;
	}*/

	mSession.put("id", userSessionId);
	mSession.save();

} else {
	if(request.getRequestURI().indexOf("/main/login.jsp") == -1
		&& request.getRequestURI().indexOf("/vod/upload.jsp") == -1
		&& request.getRequestURI().indexOf("/main/slogin.jsp") == -1
		&& request.getRequestURI().indexOf("/site/site_template.jsp") == -1
		&& request.getRequestURI().indexOf("/site/site_maildir.jsp") == -1
		&& (request.getRequestURI().indexOf("/user/sleep_insert.jsp") == -1 || !"log".equals(m.rs("after")))
	) {
		m.jsReplace(auth.loginURL, "top");
		return;
	}
}

MenuDao Menu = new MenuDao(p, siteId, "default");
SiteMenuDao SiteMenu = new SiteMenuDao();

boolean superBlock = "S".equals(userKind);
boolean adminBlock = "S".equals(userKind) || "A".equals(userKind);
boolean courseManagerBlock = "C".equals(userKind);
boolean deptManagerBlock = "D".equals(userKind);

//boolean isAuthCrm = superBlock || (-1 < siteinfo.s("auth_crm").indexOf("|" + userKind + "|"));
boolean isAuthCrm = superBlock || Menu.accessible(-999, userId, userKind, false);

//\ub85c\uadf8\uc544\uc6c3-\uacfc\uc815\uc6b4\uc601\uc790
if(courseManagerBlock && "".equals(manageCourses) && request.getRequestURI().indexOf("/main/logout.jsp") == -1) {
	m.jsAlert("\ub2f4\ub2f9\ud55c \uacfc\uc815\uc774 \uc5c6\uc2b5\ub2c8\ub2e4.\\n \uad00\ub9ac\uc790\uc5d0\uac8c \ubb38\uc758\ud558\uc138\uc694.");
	m.jsReplace("/sysop/main/logout.jsp", "top");
	return;
}

//\ub9e4\ub274\uc5bc
ManualDao Manual = new ManualDao();
int ManualId = Menu.getOneInt("SELECT manual_id FROM " + Menu.table + " WHERE link = '" + m.replace(request.getRequestURI(), "/sysop", "..") + "'");
if(0 < ManualId) {
	int ManualStatus = Manual.getOneInt("SELECT status FROM " + Manual.table + " WHERE id = " + ManualId);
	if(0 < ManualStatus) p.setVar("SYS_MENU_MANUAL_ID", ManualId);
}

p.setVar("WEB_URL", webUrl);
p.setVar("FRONT_URL", siteDomain);
p.setVar("SYS_TITLE", winTitle);
p.setVar("SYS_USERKIND", userKind);
p.setVar("SITE_INFO", siteinfo);
//p.setVar("SITE_CONFIG", siteconfig);
p.setVar("IS_AUTH_CRM", isAuthCrm);
p.setVar("IS_DEV_SERVER", isDevServer);
p.setVar("SYS_LOCALE", sysLocale);
p.setVar("SYS_TODAY", sysToday);
p.setVar("SYS_NOW", sysNow);
p.setVar("SYS_COMMON_CDN", !isDevServer ? "//cdn.malgnlms.com" : "");

p.setVar("user_master_block", isUserMaster || isMalgnOffice);
p.setVar("super_malgn_block", isMalgnOffice && siteinfo.i("super_id") == userId);
p.setVar("malgn_office_block", isMalgnOffice);
p.setVar("super_block", superBlock);
p.setVar("admin_block", adminBlock);
p.setVar("course_manager_block", courseManagerBlock);
p.setVar("dept_manager_block", deptManagerBlock);
p.setVar("SYS_URL", surl);

boolean isBlindUser = !sysToday.equals(pagreeDate);
p.setVar("SYS_BLINDUSER", isBlindUser);

UserSessionDao UserSession = new UserSessionDao();
UserSession.setSiteId(siteId);
UserSession.setType("sysop");
if(userId != 0 && !"SYSLOGIN".equals(userSessionId) && "N".equals(siteinfo.s("dup_sysop_yn")) && ("".equals(userSessionId) || userSessionId == null || !UserSession.isValid(userSessionId, userId))) {
	if(request.getRequestURI().indexOf("/sysop/main/logout.jsp") == -1) {
		m.jsAlert("\uc138\uc158\uc774 \ub9cc\ub8cc\ub418\uc5c8\uac70\ub098 \uc911\ubcf5 \ub85c\uadf8\uc778\uc774 \ub418\uc5b4 \uc790\ub3d9\uc73c\ub85c \ub85c\uadf8\uc544\uc6c3 \ub429\ub2c8\ub2e4.");
		m.jsReplace("/sysop/main/logout.jsp?mode=session", "top");
		return;
	}
}

InfoLogDao _log = new InfoLogDao(siteId); _log.setItems(userId, "B", surl, userIp);
InfoUserDao _logUser = new InfoUserDao(siteId);


      

String ch = "sysop";


      

//\uc811\uadfc\uad8c\ud55c
if(!Menu.accessible(19, userId, userKind)) { m.jsError("\uc811\uadfc \uad8c\ud55c\uc774 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }

//\uac1d\uccb4
UserDao user = new UserDao(); user.setInsertIgnore(true);
UserDeptDao userDept = new UserDeptDao();

//\ud3fc\uccb4\ud06c
f.addElement("code_yn", "N", "hname:'\ud68c\uc6d0\uc18c\uc18d\ucf54\ub4dc \uc0ac\uc6a9\uc5ec\ubd80'");
f.addElement("dept_id", null, "hname:'\ud68c\uc6d0\uc18c\uc18d', required:'Y'");
f.addElement("file", null, "hname:'\ud30c\uc77c', required:'Y', allow:'xls'");

//\ub4f1\ub85d
if(m.isPost()) {

	//\ubc30\uc5f4
	String[] fields = { "col0=>login_id", "col1=>user_nm", "col2=>passwd", "col3=>email", "col4=>mobile", "col5=>birthday", "col6=>gender", "col7=>dept_id", "col8=>zipcode", "col9=>new_addr", "col10=>addr_dtl", "col11=>reg_date", "col12=>etc1", "col13=>etc2", "col14=>etc3", "col15=>etc4", "col16=>etc5"};

	String[] required = { "col0", "col1", "col2" };

	String path = dataDir + "/tmp/user.xls";
	File f1 = f.saveFile("file", path);
	if(f1 == null) {
		m.jsAlert("\uc5d1\uc140\ud30c\uc77c\uc744 \uc77d\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4.");
		return;
	}

	DataSet records = new DataSet();

	records = new ExcelReader(path).getDataSet(1);

	if(!"".equals(path)) m.delFile(path);

	Hashtable<String, Integer> deptCodeMap = new Hashtable<String, Integer>();
	Hashtable<Integer, String> deptNameMap = new Hashtable<Integer, String>();
	DataSet dlist = userDept.find("site_id = " + siteId + " AND status = 1");
	while(dlist.next()) {
		int deptId = dlist.i("id");
		String deptCd = dlist.s("dept_cd");

		if(deptCd.startsWith("|")) deptCd = deptCd.substring(1);
		if(deptCd.endsWith("|")) deptCd = deptCd.substring(0, deptCd.length() - 1);

		String[] temp = m.split("|", deptCd);
		for(int i = 0; i < temp.length; i++) {
			deptCodeMap.put(temp[i], deptId);
		}
		deptNameMap.put(deptId, dlist.s("dept_nm"));
	}

	//\ubaa9\ub85d
	if("register".equals(f.get("mode"))) {

		//\ubcc0\uc218
		int success = 0;

		//\ud3fc\uc785\ub825
		user.item("site_id", siteId);
		user.item("conn_date", m.time("yyyyMMddHHmmss"));
		user.item("reg_date", m.time("yyyyMMddHHmmss"));
		user.item("status", 1);
		user.item("user_kind", "U"); //\ud68c\uc6d0

		int i = 0;
		while(records.next()) {
			boolean flag = true;
			for(int j = 0; j < required.length; j++) {
				if("".equals(records.s(required[j]))) flag = false;
			}

			//if(flag) flag = 0 == user.findCount("login_id = '" + records.s("col0") + "'");

			if(flag) {

				if("Y".equals(f.get("code_yn"))) records.put("col7", deptCodeMap.containsKey(records.s("col7")) ? deptCodeMap.get(records.s("col7")).intValue() : 0);
				int deptId = deptNameMap.containsKey(records.i("col7")) ? records.i("col7") : f.getInt("dept_id");
				/*
				int deptId = (
					records.i("col7") > 0 && 0 < userDept.findCount("id = " + records.i("col7") + " AND site_id = " + siteId + " AND status = 1")
					? records.i("col7")
					: f.getInt("dept_id")
				);
				*/
				String birthday = (8 != records.s("col5").length() ? m.time("yyyyMMdd") : m.time("yyyyMMdd", records.s("col5")));
				String regDate = (19 != records.s("col11").length() ? m.time("yyyyMMddHHmmss") : m.time("yyyyMMddHHmmss", records.s("col11")));

				user.item("dept_id", deptId);
				user.item("login_id", records.s("col0").toLowerCase());
				user.item("user_nm", records.s("col1"));
				user.item("passwd", m.encrypt(records.s("col2"), "SHA-256"));
				user.item("email", records.s("col3"));
				user.item("mobile", !"".equals(records.s("col4")) ? SimpleAES.encrypt(records.s("col4")) : "");
				user.item("zipcode", records.s("col8"));
				user.item("addr", "");
				user.item("new_addr", records.s("col9"));
				user.item("addr_dtl", records.s("col10"));
				user.item("gender", !"".equals(records.s("col6")) ? records.s("col6") : "1");
				user.item("birthday", birthday);
				user.item("conn_date", regDate);
				user.item("reg_date", regDate);
				user.item("etc1", records.s("col12"));
				user.item("etc2", records.s("col13"));
				user.item("etc3", records.s("col14"));
				user.item("etc4", records.s("col15"));
				user.item("etc5", records.s("col16"));

				if(user.insert()) success++;
				
			}
		}
		
		m.jsAlert("\ucd1d " + success + "\uac1c\uac00 \ub4f1\ub85d\ub410\uc2b5\ub2c8\ub2e4.\\n\ub4f1\ub85d\ub41c \ub370\uc774\ud130\ub97c \ud655\uc778\ud574\uc8fc\uc138\uc694.");

		m.jsReplace("user_list.jsp", "parent");
		return;

	} else if("list".equals(f.get("mode"))) {

		//\ud3ec\ub9f7\ud305
		DataSet list = new DataSet();
		DataSet tmp = m.arr2loop(fields);
		int i = 0;
		while(records.next()) {
			boolean flag = true;
			for(int j = 0; j < required.length; j++) {
				if("".equals(records.s(required[j]))) flag = false;
			}

			if(flag) {
				tmp.first();
				while(tmp.next()) {
					records.put(tmp.s("name"), records.s(tmp.s("id")));
				}

				if("Y".equals(f.get("code_yn"))) records.put("dept_id", deptCodeMap.containsKey(records.s("dept_id")) ? deptCodeMap.get(records.s("dept_id")).intValue() : 0);
				int deptId = deptNameMap.containsKey(records.i("dept_id")) ? records.i("dept_id") : f.getInt("dept_id");
				/*
				int deptId = (
					records.i("dept_id") > 0 && 0 < userDept.findCount("id = " + records.i("dept_id") + " AND site_id = " + siteId + " AND status = 1")
					? records.i("dept_id")
					: f.getInt("dept_id")
				);
				*/
				records.put("dept_id", deptId);
				//records.put("dept_nm_conv", userDept.getNames(deptId));
				records.put("dept_nm_conv", deptNameMap.get(deptId));
				records.put("gender_conv", m.getItem(!"".equals(records.s("gender")) ? records.s("gender") : "1", user.genders));
				records.put("__ord", ++i);

				list.addRow(records.getRow());
			}
			if(i == 20) break;
		}

		//\ucd9c\ub825
		p.setLayout("blank");
		p.setBody("user.user_excel");
		p.setVar("query", m.qs());
		p.setVar("list_query", m.qs("id"));
		p.setVar("form_script", f.getScript());
		p.setVar("dept_id", f.get("dept_id"));
		p.setVar("code_yn", f.get("code_yn"));

		p.setLoop("list", list);
		p.setVar("list_area", true);
		p.display();

		return;
	}
}

//\ucd9c\ub825
p.setBody("user.user_excel");
p.setVar("p_title", "\ud68c\uc6d0\uc77c\uad04 \ub4f1\ub85d");
p.setVar("query", m.qs());
p.setVar("list_query", m.qs("id"));
p.setVar("form_script", f.getScript());

p.setLoop("dept_list", userDept.getList(siteId));
p.setVar("upload_area", true);
p.display();


    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6749855747778707107L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/user/user_excel.jsp"), -1420985395145809585L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/user/init.jsp"), -7162420496711387185L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/init.jsp"), 1160630992102546501L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
}
