/*
 * JSP generated by Resin-3.1.15 (built Mon, 13 Oct 2014 06:45:33 PDT)
 */

package _jsp._project;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _user_0modify__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    try {
      

//\uac1d\uccb4
Malgn m = new Malgn(request, response, out);
SessionDao mSession = new SessionDao(request, response);

Form f = new Form("form1");
try { f.setRequest(request); }
catch(Exception ex) { out.print("Overflow file size. - " + ex.getMessage()); return; }

Page p = new Page();
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);

//\ubcc0\uc218
int userId = 0;
String loginId = "";
String userName = "";
String userEmail = "";
String userType = "";
String sysToday = m.time("yyyyMMdd");
String sysNow = m.time("yyyyMMddHHmmss");
String userSessionId = null;
boolean loginBlock = false;

//\ub85c\uadf8\uc778 \uc5ec\ubd80 \uccb4\ud06c
Auth auth = new Auth(request, response);
auth.loginURL = "/main/login.jsp";
auth.keyName = "gidon";

if(auth.isValid()) {
    userId = auth.getInt("ID");
    loginId = auth.getString("LOGINID");
    userName = auth.getString("USERNAME");
    userEmail = auth.getString("EMAIL");
    userType = auth.getString("TYPE");

    userSessionId = auth.getString("SESSIONID");
}

p.setVar("SYS_LOGINID", loginId);
p.setVar("SYS_USERNAME", userName);
p.setVar("SYS_USEREMAIL", userEmail);
p.setVar("SYS_USERKIND", userType);
p.setVar("SYS_TODAY", sysToday);
p.setVar("SYS_NOW", sysNow);


      

    String ch = "project";


      

//\uae30\ubcf8\ud0a4
int id = m.ri("id");
if(id == 0 ){ m.jsError("\uae30\ubcf8\ud0a4\ub294 \ubc18\ub4dc\uc2dc \uc9c0\uc815\ud574\uc57c \ud569\ub2c8\ub2e4."); }

//\uac1d\uccb4
UserDao user = new UserDao();

//\uc815\ubcf4
DataSet info = user.find("id = " + id + " AND status != -1");
if(!info.next()) { m.jsError("\ud574\ub2f9 \uc815\ubcf4\uac00 \uc5c6\uc2b5\ub2c8\ub2e4."); }

//\ud3fc\uccb4\ud06c
f.addElement("login_id", info.s("login_id"), "hname:'\ud68c\uc6d0\uc544\uc774\ub514', required:'Y'");
//f.addElement("dept_id", null, "hname:'\uc18c\uc18d'");
f.addElement("user_nm", info.s("login_id"), "hname:'\ud68c\uc6d0\uba85', required:'Y'");
f.addElement("passwd", null, "hname:'\ube44\ubc00\ubc88\ud638', required:'Y', match:'passwd2', minbyte:'4', maxbyte:'20'");
f.addElement("birthday", m.time("yyyy-MM-dd", info.s("birthday")), "hname:'\uc0dd\ub144\uc6d4\uc77c'");
f.addElement("email1", m.split("@", info.s("email"), 2)[0], "hname:'\uc774\uba54\uc77c', option:'email', glue:'email2', delim:'@'");
f.addElement("email2", m.split("@", info.s("email"), 2)[1], "hname:'\uc774\uba54\uc77c'");
f.addElement("zipcode", info.s("zipcode"), "hname:'\uc6b0\ud3b8\ubc88\ud638'");
//f.addElement("addr", null, "hname:'\uad6c\uc8fc\uc18c'");
f.addElement("new_addr", info.s("addr"), "hname:'\uc8fc\uc18c'");
f.addElement("addr_dtl", info.s("new_addr"), "hname:'\uc0c1\uc138\uc8fc\uc18c'");


//\ub4f1\ub85d
if(m.isPost() && f.validate()) {

    //\ubcc0\uc218-\uc774\uba54\uc77c
    String email = f.glue("@", "email1, email2");
    if("@".equals(email)) email = "";

    int newId = user.getSequence();
    user.item("id", newId);
//    user.item("dept_id", f.get("dept_id"));
    user.item("login_id", f.get("login_id").toLowerCase());
    user.item("user_nm", f.get("user_nm"));
    if(!"".equals(f.get("passwd"))) user.item("passwd", m.encrypt(f.get("passwd"), "SHA-256"));
    user.item("email", email);
    user.item("zipcode", f.get("zipcode"));
    user.item("new_addr", f.get("new_addr"));
    user.item("addr_dtl", f.get("addr_dtl"));
    user.item("birthday", Malgn.time("yyyyMMdd", f.get("birthday")));
//    user.item("conn_date", sysNow);
    user.item("status", f.getInt("status"));
    if(!user.update("id = " + id + "")) { m.jsAlert("\ub4f1\ub85d\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }

    m.jsReplace("index.jsp?" + m.qs("id"), "parent");
    return;

}
p.setLayout("project");
p.setBody("project.user_insert");
p.setVar("query", m.qs());
p.setVar("list_query", m.qs("id"));
p.setVar("form_script", f.getScript());

p.setVar("modify", true);
p.setVar(info);

p.display();


    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6749855747778707107L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("project/user_modify.jsp"), 1834247712280271595L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("project/init.jsp"), 8464605810316084892L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("init.jsp"), 7685309690132995048L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
}
