/*
 * JSP generated by Resin-3.1.15 (built Mon, 13 Oct 2014 06:45:33 PDT)
 */

package _jsp._sysop._crm;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import java.io.*;
import dao.*;
import malgnsoft.db.*;
import malgnsoft.util.*;

public class _user_0modify__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    try {
      

String docRoot = Config.getDocRoot();
String jndi = Config.getJndi();
String tplRoot = Config.getDocRoot() + "/sysop/html";

Malgn m = new Malgn(request, response, out);

Form f = new Form("form1");
try { f.setRequest(request); } catch (Exception ex) { out.print("\uc81c\ud55c \uc6a9\ub7c9 \ucd08\uacfc - " + ex.getMessage()); return; }

Page p = new Page(tplRoot);
p.setRequest(request);
p.setPageContext(pageContext);
p.setWriter(out);
p.setBaseRoot("/home/lms/public_html/html");

SiteDao Site = new SiteDao();
DataSet siteinfo = Site.getSiteInfo(request.getServerName(), "sysop");
SiteConfigDao SiteConfig = new SiteConfigDao(siteinfo.i("id"));
if(1 != siteinfo.i("sysop_status") || "".equals(siteinfo.s("doc_root"))) { m.jsReplace("/main/guide.jsp", "top"); return; }
//Hashtable<String, String> siteconfig = SiteConfig.getSiteConfig(siteinfo.s("id"));

String siteDomain = request.getScheme() + "://" + request.getServerName();
int port = request.getServerPort();
if(port != 80) siteDomain += ":" + port;
String webUrl = siteDomain + "/sysop";

String dataDir = siteinfo.s("doc_root") + "/data";
f.dataDir = dataDir;
m.dataDir = dataDir;
m.dataUrl = Config.getDataUrl() + (!"/data".equals(Config.getDataUrl()) ? siteinfo.s("ftp_id") : "");

boolean isDevServer = -1 < request.getServerName().indexOf("lms.malgn.co.kr");
siteinfo.put("logo_url", (!"/data".equals(Config.getDataUrl()) ? "" : siteDomain) + m.getUploadUrl(siteinfo.s("logo")));

//IP\ucc28\ub2e8
String userIp = request.getRemoteAddr();
boolean isMalgnOffice = "115.91.52.203".equals(userIp) || "115.91.52.204".equals(userIp) || "125.128.232.145".equals(userIp) || "59.5.222.106".equals(userIp);
if(!"".equals(siteinfo.s("allow_ip_sysop")) && !isMalgnOffice && !Site.checkIP(userIp, siteinfo.s("allow_ip_sysop"))) {
	m.redirect("/");
	return;
}

//\uc5b8\uc5b4
String sysLocale = "".equals(siteinfo.s("locale")) ? "default" : siteinfo.s("locale");
//String sysLocale = "default";
Message _message = new Message(sysLocale);
_message.reloadAll();
m.setMessage(_message);
//p.setMessage(_message);

//\uae30\ubcf8 \ud68c\uc6d0\uc815\ubcf4
int siteId = siteinfo.i("id");
int userId = 0;
String loginId = "";
String userName = "";
String userKind = "";
int userDeptId = 0;
String userGroups = "";
String manageCourses = "";
String userSessionId = "";
boolean isUserMaster = false;
String winTitle = "[\uad00\ub9ac\uc790] " + siteinfo.s("site_nm");
String sysToday = m.time("yyyyMMdd");
String sysNow = m.time("yyyyMMddHHmmss");

//SessionDao mSession = new SessionDao("sysop");
SessionDao mSession = new SessionDao(request, response);
//mSession.setId(session.getId());
mSession.setSiteId(siteId);

//\ub85c\uadf8\uc778 \uc5ec\ubd80\ub97c \uccb4\ud06c
Auth auth = new Auth(request, response);
auth.loginURL = "/sysop/main/login.jsp";
auth.keyName = "MLMSKEY2014" + siteId + "7";
if(0 < siteinfo.i("sysop_session_hour")) auth.setValidTime(siteinfo.i("sysop_session_hour") * 60);
if(auth.isValid()) {
	userId = m.parseInt(auth.getString("ID"));
	loginId = auth.getString("LOGINID");
	userName = auth.getString("NAME");
	userKind = auth.getString("KIND");
	userDeptId = auth.getInt("DEPT");
	userGroups = auth.getString("GROUPS");
	manageCourses = auth.getString("MANAGE_COURSES");
	userSessionId = userSessionId = auth.getString("SESSIONID");
	isUserMaster = "Y".equals(auth.getString("IS_USER_MASTER"));
	if("SYSLOGIN".equals(userSessionId)) siteinfo.put("dup_sysop_yn", "Y");

	mSession.setId(userSessionId);
	mSession.setUserId(userId);

} else {
	if(request.getRequestURI().indexOf("/main/login.jsp") == -1
		&& request.getRequestURI().indexOf("/vod/upload.jsp") == -1
		&& request.getRequestURI().indexOf("/main/slogin.jsp") == -1
		&& request.getRequestURI().indexOf("/site/site_template.jsp") == -1
		&& request.getRequestURI().indexOf("/site/site_maildir.jsp") == -1
		&& (request.getRequestURI().indexOf("/user/sleep_insert.jsp") == -1 || !"log".equals(m.rs("after")))
	) {
		m.jsReplace(auth.loginURL, "top");
		return;
	}
}

MenuDao Menu = new MenuDao(p, siteId, "default");
SiteMenuDao SiteMenu = new SiteMenuDao();

boolean superBlock = "S".equals(userKind);
boolean adminBlock = "S".equals(userKind) || "A".equals(userKind);
boolean courseManagerBlock = "C".equals(userKind);
boolean deptManagerBlock = "D".equals(userKind);

//boolean isAuthCrm = superBlock || (-1 < siteinfo.s("auth_crm").indexOf("|" + userKind + "|"));
boolean isAuthCrm = superBlock || Menu.accessible(-999, userId, userKind, false);

//\ub85c\uadf8\uc544\uc6c3-\uacfc\uc815\uc6b4\uc601\uc790
if(courseManagerBlock && "".equals(manageCourses) && request.getRequestURI().indexOf("/main/logout.jsp") == -1) {
	m.jsAlert("\ub2f4\ub2f9\ud55c \uacfc\uc815\uc774 \uc5c6\uc2b5\ub2c8\ub2e4.\\n \uad00\ub9ac\uc790\uc5d0\uac8c \ubb38\uc758\ud558\uc138\uc694.");
	m.jsReplace("/sysop/main/logout.jsp", "top");
	return;
}

//\ub9e4\ub274\uc5bc
ManualDao Manual = new ManualDao();
int ManualId = Menu.getOneInt("SELECT manual_id FROM " + Menu.table + " WHERE link = '" + m.replace(request.getRequestURI(), "/sysop", "..") + "'");
if(0 < ManualId) {
	int ManualStatus = Manual.getOneInt("SELECT status FROM " + Manual.table + " WHERE id = " + ManualId);
	if(0 < ManualStatus) p.setVar("SYS_MENU_MANUAL_ID", ManualId);
}

p.setVar("WEB_URL", webUrl);
p.setVar("FRONT_URL", siteDomain);
p.setVar("SYS_TITLE", winTitle);
p.setVar("SYS_USERKIND", userKind);
p.setVar("SITE_INFO", siteinfo);
//p.setVar("SITE_CONFIG", siteconfig);
p.setVar("IS_AUTH_CRM", isAuthCrm);
p.setVar("IS_DEV_SERVER", isDevServer);
p.setVar("SYS_LOCALE", sysLocale);
p.setVar("SYS_TODAY", sysToday);
p.setVar("SYS_NOW", sysNow);
p.setVar("SYS_COMMON_CDN", !isDevServer ? "//cdn.malgnlms.com" : "");

p.setVar("user_master_block", isUserMaster || isMalgnOffice);
p.setVar("malgn_office_block", isMalgnOffice);
p.setVar("super_block", superBlock);
p.setVar("admin_block", adminBlock);
p.setVar("course_manager_block", courseManagerBlock);
p.setVar("dept_manager_block", deptManagerBlock);

UserSessionDao UserSession = new UserSessionDao();
UserSession.setSiteId(siteId);
UserSession.setType("sysop");
if(userId != 0 && "N".equals(siteinfo.s("dup_sysop_yn")) && ("".equals(userSessionId) || userSessionId == null || !UserSession.isValid(userSessionId, userId))) {
	if(request.getRequestURI().indexOf("/sysop/main/logout.jsp") == -1) {
		m.jsAlert("\uc138\uc158\uc774 \ub9cc\ub8cc\ub418\uc5c8\uac70\ub098 \uc911\ubcf5 \ub85c\uadf8\uc778\uc774 \ub418\uc5b4 \uc790\ub3d9\uc73c\ub85c \ub85c\uadf8\uc544\uc6c3 \ub429\ub2c8\ub2e4.");
		m.jsReplace("/sysop/main/logout.jsp?mode=session", "top");
		return;
	}
}


      

String ch = m.rs("ch", "crm");

//\uac1d\uccb4
UserDao user = new UserDao();
UserDeptDao userDept = new UserDeptDao();

//\uc81c\ud55c
if(!isAuthCrm) { m.jsErrClose("\uc811\uadfc\uc774 \uac70\ubd80 \ub418\uc5c8\uc2b5\ub2c8\ub2e4."); return; }

//\uc815\ubcf4
DataSet uinfo = user.find("id = " + userId + " AND user_kind IN ('C', 'D', 'A', 'S') AND status = 1");
if(!uinfo.next()) { m.jsErrClose("\uc811\uadfc\uc774 \uac70\ubd80 \ub418\uc5c8\uc2b5\ub2c8\ub2e4."); return; }

//\uae30\ubcf8\ud0a4
String uid = m.rs("uid");
if("".equals(uid)) { m.jsErrClose("\uae30\ubcf8\ud0a4\ub294 \ubc18\ub4dc\uc2dc \uc9c0\uc815\ud574\uc57c \ud569\ub2c8\ub2e4."); return; }

//\uc81c\ud55c-\uc18c\uc18d\uc6b4\uc601\uc790\ubcf8\uc778\uc18c\uc18d\ub9cc
if("D".equals(userKind) && 1 > user.findCount("id = " + uid + " AND site_id = " + siteId + " AND dept_id IN (" + userDept.getSubIdx(siteId, userDeptId) + ") AND status != -1")) {
	m.jsErrClose("\uc811\uadfc\uc774 \uac70\ubd80 \ub418\uc5c8\uc2b5\ub2c8\ub2e4."); return;
}

if(!"".equals(siteinfo.s("pubtree_token"))) {
	p.setVar("ebook_block", true);
}


      

//\uac1d\uccb4
UserOutDao userOut = new UserOutDao();
UserSleepDao userSleep = new UserSleepDao();
//UserDeptDao userDept = new UserDeptDao();
TutorDao tutor = new TutorDao();
ActionLogDao actionLog = new ActionLogDao();
FileDao file = new FileDao();

//\uc815\ubcf4
DataSet info = user.query(
	" SELECT a.*, t.tutor_nm, t.name_en, t.attached, t.tutor_file, t.ability, t.university, t.major, t.introduce, t.bank_nm, t.bank_account "
	+ " FROM " + user.table + " a "
	+ " LEFT JOIN " + tutor.table + " t ON a.id = t.user_id AND t.status != -1 "
	+ " WHERE a.id = " + uid + " AND a.site_id = " + siteId + " AND a.status != -1"
);
if(!info.next()) { m.jsError("\ud574\ub2f9 \ud68c\uc6d0\uc815\ubcf4\uac00 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }
info.put("reg_date_conv", m.time("yyyy.MM.dd HH:mm", info.s("reg_date")));
info.put("sleep_date_conv", m.time("yyyy.MM.dd HH:mm", info.s("sleep_date")));
info.put("conn_date_conv", m.time("yyyy.MM.dd HH:mm", info.s("conn_date")));
info.put("status_conv", m.getItem(info.s("status"), user.statusList));

//\ud30c\uc77c\uc0ad\uc81c
if("fdel".equals(m.rs("mode"))) {
	if(!"".equals(info.s("tutor_file"))) {
		tutor.item("tutor_file", "");
		if(!tutor.update("user_id = " + uid + "")) { }
		m.delFileRoot(m.getUploadPath(info.s("tutor_file")));
	}
	return;
}

//\ubcc0\uc218
boolean superModifyBlock = "S".equals(userKind) || (!"S".equals(info.s("user_kind")) && userId != info.i("id"));
boolean sleepBlock = (31 == info.i("status"));
boolean outBlock = adminBlock && info.i("id") != userId;
DataSet sinfo = new DataSet();

if(sleepBlock) {
	//\ud734\uba74\uc815\ubcf4
	sinfo = userSleep.find("id = " + uid + " AND site_id = " + siteId + " AND status != -1");
	if(!sinfo.next()) { m.jsErrClose("\ud574\ub2f9 \ud734\uba74\ud68c\uc6d0\uc815\ubcf4\uac00 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }
	sinfo.put("dept_nm", userDept.getOne("SELECT dept_nm FROM " + userDept.table + " WHERE id = " + sinfo.s("dept_id")));
	sinfo.put("gender_conv", m.getItem(sinfo.s("gender"), user.genders));
	sinfo.put("birthday_conv", m.time("yyyy.MM.dd", sinfo.s("birthday")));
	if(!"".equals(sinfo.s("mobile"))) try { sinfo.put("mobile_conv", SimpleAES.decrypt(sinfo.s("mobile"))); } catch(Exception e) { }

} else {
	//\ud3fc\uccb4\ud06c
	f.addElement("user_nm", info.s("user_nm"), "hname:'\ud68c\uc6d0\uba85', required:'Y'");
	if(superBlock && superModifyBlock) f.addElement("user_kind", info.s("user_kind"), "hname:'\ud68c\uc6d0\uad6c\ubd84'");
	if(adminBlock) f.addElement("dept_id", info.s("dept_id"), "hname:'\uc18c\uc18d', required:'Y'");
	f.addElement("tutor_yn", info.s("tutor_yn"), "hname:'\uac15\uc0ac\uc5ec\ubd80'");
	f.addElement("passwd", null, "hname:'\ube44\ubc00\ubc88\ud638', match:'passwd2'");
	f.addElement("passwd2", null, "hname:'\ube44\ubc00\ubc88\ud638'");
	f.addElement("passwd_date", m.time("yyyy-MM-dd", info.s("passwd_date")), "hname:'\ube44\ubc00\ubc88\ud638 \ubcc0\uacbd\uc548\ub0b4\uc77c'");
	f.addElement("gender", info.s("gender"), "hname:'\uc131\ubcc4', required:'Y', option:'number'");
	f.addElement("birthday", m.time("yyyy-MM-dd", info.s("birthday")), "hname:'\uc0dd\ub144\uc6d4\uc77c'");
	String mobile = "";
	if(!"".equals(info.s("mobile"))) try { mobile = SimpleAES.decrypt(info.s("mobile")); } catch(Exception e) { }
	f.addElement("mobile", mobile, "hname:'\ud734\ub300\uc804\ud654'");
	f.addElement("email", info.s("email"), "hname:'\uc774\uba54\uc77c', option:'email'");
	f.addElement("zipcode", info.s("zipcode"), "hname:'\uc6b0\ud3b8\ubc88\ud638'");
	//f.addElement("addr", info.s("addr"), "hname:'\uc8fc\uc18c'");
	f.addElement("new_addr", info.s("new_addr"), "hname:'\uc8fc\uc18c'");
	f.addElement("addr_dtl", info.s("addr_dtl"), "hname:'\uc0c1\uc138\uc8fc\uc18c'");
	f.addElement("etc1", info.s("etc1"), "hname:'\uae30\ud0c01'");
	f.addElement("etc2", info.s("etc2"), "hname:'\uae30\ud0c02'");
	f.addElement("etc3", info.s("etc3"), "hname:'\uae30\ud0c03'");
	f.addElement("etc4", info.s("etc4"), "hname:'\uae30\ud0c04'");
	f.addElement("etc5", info.s("etc5"), "hname:'\uae30\ud0c05'");
	f.addElement("status", info.i("status"), "hname:'\uc0c1\ud0dc', option:'number'");

	f.addElement("display_yn", info.s("display_yn"), "hname:'\uac15\uc0ac\ub178\ucd9c\uc5ec\ubd80'");
	f.addElement("name_en", info.s("name_en"), "hname:'\uac15\uc0ac\uba85(\uc601\ubb38)'");
	f.addElement("attached", info.s("attached"), "hname:'\uc18c\uc18d'");
	f.addElement("ability", null, "hname:'\uacbd\ub825\uc0ac\ud56d'");
	f.addElement("major", info.s("major"), "hname:'\uc804\uacf5'");
	f.addElement("university", info.s("university"), "hname:'\ucd5c\uc885\ud559\ub825'");
	f.addElement("introduce", null, "hname:'\uc18c\uac1c'");
	f.addElement("bank_nm", info.s("bank_nm"), "hname:'\uc740\ud589\uba85'");
	f.addElement("bank_account", info.s("bank_account"), "hname:'\uacc4\uc88c\ubc88\ud638'");
	f.addElement("tutor_file", null, "hname:'\uc0ac\uc9c4', allow:'jpg|gif|jpeg|png'");
}

//\uc218\uc815
if(m.isPost() && f.validate()) {

	//\uc0ad\uc81c
	if("-2".equals(f.get("status"))) {
		if(!outBlock) { m.jsAlert("\uad8c\ud55c\uc774 \uc5c6\uc2b5\ub2c8\ub2e4."); return; }

		//\uc218\uc815
		user.item("passwd", "");
		user.item("status", -2);
		if(!user.update("id = " + uid + " AND site_id = " + siteId)) { m.jsAlert("\uc218\uc815\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }

		//\uc138\uc158\uc0ad\uc81c
		mSession.delSession(mSession.getSessionId(m.parseInt(uid), "user"));
		mSession.delSession(mSession.getSessionId(m.parseInt(uid), "sysop"));

		//\ud0c8\ud1f4\ub4f1\ub85d
		userOut.item("user_id", uid);
		userOut.item("site_id", siteId);
		userOut.item("out_type", "ETC");
		userOut.item("memo", "CRM \ud0c8\ud1f4");
		userOut.item("admin_id", userId);
		userOut.item("out_date", m.time("yyyyMMddHHmmss"));
		userOut.item("reg_date", m.time("yyyyMMddHHmmss"));
		userOut.item("status", 1);
		if(!userOut.replace()) { m.jsAlert("\ub4f1\ub85d\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }

		//\uc774\ub3d9
		m.js("parent.parent.opener.location.reload();");
		m.jsErrClose("\ud0c8\ud1f4\ucc98\ub9ac \ub418\uc5c8\uc2b5\ub2c8\ub2e4.", "parent.parent");
		return;

	//\ube44\ubc00\ubc88\ud638\uc218\uc815/\uc138\uc158\uc0ad\uc81c
	} else if(!"".equals(f.get("passwd"))) {
		//\uc81c\ud55c-\ube44\ubc00\ubc88\ud638
		if(!f.get("passwd").matches("^(?=.*?[A-Za-z])(?=.*?[0-9])(?=.*?[\\W_]).{8,}$")) {
			m.jsAlert("\ube44\ubc00\ubc88\ud638\ub294 \uc601\ubb38, \uc22b\uc790, \ud2b9\uc218\ubb38\uc790 \uc870\ud569 8\uc790 \uc774\uc0c1 \uc785\ub825\ud558\uc138\uc694.");
			return;
		}

		user.item("passwd", m.encrypt(f.get("passwd"), "SHA-256"));
		mSession.delSession(mSession.getSessionId(info.i("id"), "user"));
		mSession.delSession(mSession.getSessionId(info.i("id"), "sysop"));
	}

	user.item("user_nm", f.get("user_nm"));
	if(superBlock && superModifyBlock) user.item("user_kind", f.get("user_kind"));
	if(adminBlock) user.item("dept_id", f.get("dept_id"));
	user.item("tutor_yn", f.get("tutor_yn", "N"));
	user.item("gender", f.getInt("gender"));
	user.item("birthday", m.time("yyyyMMdd", f.get("birthday")));
	user.item("mobile", !"".equals(f.get("mobile")) ? SimpleAES.encrypt(f.get("mobile")) : "");
	user.item("email", f.get("email"));
	user.item("zipcode", f.get("zipcode"));
	//user.item("addr", f.get("addr"));
	user.item("new_addr", f.get("new_addr"));
	user.item("addr_dtl", f.get("addr_dtl"));
	user.item("etc1", f.get("etc1"));
	user.item("etc2", f.get("etc2"));
	user.item("etc3", f.get("etc3"));
	user.item("etc4", f.get("etc4"));
	user.item("etc5", f.get("etc5"));
	user.item("display_yn", f.get("display_yn"));
	if(superModifyBlock) user.item("status", f.getInt("status"));

	if(!user.update("id = " + uid + "")) { m.jsAlert("\uc218\uc815\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }

	if("Y".equals(f.get("tutor_yn"))) {
		tutor.item("user_id", uid);
		tutor.item("site_id", siteId);
		tutor.item("tutor_nm", f.get("user_nm"));
		tutor.item("name_en", f.get("name_en"));
		tutor.item("attached", f.get("attached"));

		if(null != f.getFileName("tutor_file")) {
			File f1 = f.saveFile("tutor_file");
			if(f1 != null) {
				tutor.item("tutor_file", f.getFileName("tutor_file"));
				if(!"".equals(info.s("tutor_file"))) m.delFileRoot(m.getUploadPath(info.s("tutor_file")));
			}
		}

		tutor.item("ability", f.get("ability"));
		tutor.item("university", f.get("university"));
		tutor.item("major", f.get("major"));
		tutor.item("introduce", f.get("introduce"));
		tutor.item("bank_nm", f.get("bank_nm"));
		tutor.item("bank_account", f.get("bank_account"));
		tutor.item("status", "1");

		if(0 < tutor.findCount("user_id = " + uid)) {
			if(!tutor.update("user_id = " + uid)) { m.jsAlert("\uac15\uc0ac\uc815\ubcf4\ub97c \uc218\uc815\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }
		} else {
			if(!tutor.insert()) { m.jsAlert("\uac15\uc0ac\uc815\ubcf4\ub97c \ub4f1\ub85d\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }
		}
	} else if(info.b("tutor_yn")) {
		tutor.item("status", "-1");
		//if(!tutor.update("user_id = " + uid + " AND status != -1")) { m.jsAlert("\uac15\uc0ac\uc815\ubcf4\ub97c \uc218\uc815\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }
	}
	
	m.jsAlert("\uc218\uc815 \ub418\uc5c8\uc2b5\ub2c8\ub2e4.");
	m.jsReplace("user_modify.jsp?" + m.qs(), "parent");
	return;
}

//\uc561\uc158\ub85c\uadf8-\uc870\ud68c
actionLog.item("site_id", siteId);
actionLog.item("user_id", userId);
actionLog.item("module", "user");
actionLog.item("module_id", uid);
actionLog.item("action_type", "R");
actionLog.item("action_desc", "\ud68c\uc6d0\uc815\ubcf4\uc870\ud68c");
actionLog.item("before_info", "");
actionLog.item("after_info", "");
actionLog.item("reg_date", m.time("yyyyMMddHHmmss"));
actionLog.item("status", 1);
if(!actionLog.insert()) { m.jsError("\ub4f1\ub85d\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); return; }

//\ud3ec\ub9f7\ud305
if(0 < info.i("dept_id")) {	
	info.put("dept_nm_conv", userDept.getNames(info.i("dept_id")));
} else {	
	info.put("dept_nm", "[\ubbf8\uc18c\uc18d]");
	info.put("dept_nm_conv", "[\ubbf8\uc18c\uc18d]");
}
info.put("tutor_file_conv", m.encode(info.s("tutor_file")));
info.put("tutor_file_url", m.getUploadUrl(info.s("tutor_file")));
info.put("tutor_file_ek", m.encrypt(info.s("tutor_file") + m.time("yyyyMMdd")));
info.put("super_modify_block", superModifyBlock);
info.put("user_kind_conv", m.getItem(info.s("user_kind"), user.kinds));
info.put("email_yn_conv", m.getItem(info.s("email_yn"), user.receiveYn));
info.put("sms_yn_conv", m.getItem(info.s("sms_yn"), user.receiveYn));
info.put("status_conv", m.getItem(info.s("status"), user.statusList));

//\ud30c\uc77c
DataSet files = file.getFileList(m.parseInt(uid), "user", true);
while(files.next()) {
	files.put("ext", file.getFileIcon(files.s("filename")));
	files.put("ek", m.encrypt(files.s("id")));
	files.put("file_url", m.getUploadUrl(files.s("filename")));
	files.put("class", -1 < files.s("filetype").indexOf("image/") ? "image01" : "");
}

//\ud734\uba74\ud574\uc81c
if("awake".equals(m.rs("mode"))) {
	if(0 >= userSleep.awakeUser(uid)) { m.jsAlert("\ud734\uba74\ud574\uc81c\ud558\ub294 \uc911 \uc624\ub958\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4."); }
	m.jsReplace("../crm/user_modify.jsp?" + m.qs("mode"), "parent");
	return;
}

//\ucd9c\ub825
p.setLayout(ch);
p.setBody("crm.user_modify");
p.setVar("p_title", !sleepBlock ? "\uc218\uc815" : "\ud734\uba74\uc815\ubcf4 \uc870\ud68c");
p.setVar("list_query", m.qs("id"));
p.setVar("query", m.qs());
p.setVar("form_script", f.getScript());
p.setVar("tab_user", "current");

p.setVar(info);
p.setVar("sinfo", sinfo);
p.setLoop("files", files);

p.setVar("out_block", outBlock);
p.setVar("sleep_block", sleepBlock);

p.setVar("SITE_CONFIG", SiteConfig.getArr(new String[] {"user_etc_", "join_"}));
p.setLoop("kinds", m.arr2loop(user.kinds));
p.setLoop("status_list", m.arr2loop(user.statusList));
p.setLoop("genders", m.arr2loop(user.genders));
//p.setLoop("dept_list", userDept.find("status = 1 AND site_id  = " + siteId + "", "*", "sort ASC"));
p.setLoop("dept_list", userDept.getList(siteId));
p.display();


    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6749855747778707107L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/crm/user_modify.jsp"), -5788993389542171830L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/crm/init.jsp"), 3274751379506181988L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysop/init.jsp"), -7592216907510913785L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
}
